name: Cache Prime Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-3bdde62

      - name: prime-cache-3bdde62
        run: |
          echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
          if [ "${{ steps.cache-step.outputs.cache-hit }}" != "true" ]; then
            echo "Priming cache..."
            mkdir -p ~/.cache/demo
            echo "cached at $(date)" > ~/.cache/demo/file.txt
          fi
